name: CD

on:
  push:
    tags:
    - v*

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore
    - run: dotnet pack --configuration Release
    - run: dotnet nuget push src\bin\Release\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
