name: CD

# Based on:
# https://sc.vern.cc/a-nuget-package-workflow-using-github-actions-7da8c6557863
# https://dusted.codes/github-actions-for-dotnet-core-nuget-packages#drive-nuget-version-from-git-tags

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Get Version from Tag
        run: |
          arrTag=(${GITHUB_REF//\// })
          VERSION="${arrTag[2]}"
          VERSION="${VERSION:1}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - run: dotnet build --configuration Release -p:Version=${VERSION}
      - run: dotnet pack --configuration Release -p:Version=${VERSION} --no-build --output .
      - run: dotnet nuget push HolzShots.Forms.Transitions.${VERSION}.nupkg --source "${NUGET_FEED}" --api-key "${NUGET_KEY}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
